accelerator: null
accumulate_grad_batches: 4
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 1
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_class: WIKI80
data_dir: dataset/historyRE
default_root_dir: null
deterministic: false
devices: null
distributed_backend: null
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: null
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
init_answer_words: 1
init_answer_words_by_one_token: 0
init_type_words: 1
ipus: null
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_class: BertLitModel
load_checkpoint: null
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 3.0e-05
lr_2: 3.0e-05
max_epochs: 10
max_seq_length: 128
max_steps: null
max_time: null
min_epochs: null
min_steps: null
model_class: RobertaForPrompt
model_name_or_path: bert-base-chinese
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 0
optimizer: AdamW
overfit_batches: 0.0
path: output/epoch=9-Eval/f1=0.51.ckpt
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
ptune_k: 7
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
seed: 7
stochastic_weight_avg: false
sync_batchnorm: false
t_gamma: 0.3
t_lambda: 0.001
task_name: wiki80
terminate_on_nan: false
tpu_cores: null
track_grad_norm: -1
truncated_bptt_steps: null
two_steps: false
use_prompt: true
use_template_words: 1
val_check_interval: 1.0
wandb: true
weight_decay: 0.01
weights_save_path: null
weights_summary: top
